# Generated by Django 4.2.13 on 2025-12-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_branch_documentlibrary_servicetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlibrary',
            name='file_url',
        ),
    ]
