# Generated by Django 4.2.13 on 2025-12-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_customer_branch_customer_destination_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sales_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sales tax percentage for this branch (e.g., 8.25 for 8.25%)', max_digits=5),
        ),
    ]
