# Generated by Django 4.2.13 on 2025-12-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_branch_sales_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('moveit', 'Moveit'), ('mymovingloads', 'MyMovingLoads'), ('moving24', 'Moving24'), ('baltic_website', 'Baltic Website'), ('n1m_website', 'N1M Website'), ('google', 'Google'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('in_progress', 'In Progress'), ('opportunity', 'Opportunity'), ('booked', 'Booked'), ('closed', 'Closed'), ('bad_lead', 'Bad Lead'), ('lost', 'Lost')], default='new_lead', max_length=50),
        ),
    ]
