# Generated by Django 4.2.13 on 2025-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_alter_customer_source_alter_customer_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='estimate_content',
            field=models.TextField(blank=True, help_text='Additional content to display on estimates for this service type', null=True),
        ),
    ]
