# Generated by Django 5.2.6 on 2026-01-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_branch_organization_customer_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlibrary',
            name='category',
            field=models.CharField(choices=[('Email', 'Email'), ('Contract', 'Contract'), ('Invoice', 'Invoice'), ('Payment Receipt', 'Payment Receipt'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='documentlibrary',
            name='subject',
            field=models.CharField(blank=True, help_text='Used specifically for Email category', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
