# Generated by Django 5.2.6 on 2026-01-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_webhookconfiguration_rawwebhooklead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlibrary',
            name='category',
            field=models.CharField(choices=[('Email', 'Email'), ('Contract', 'Contract'), ('Invoice', 'Invoice'), ('Payment Receipt', 'Payment Receipt'), ('Work Order', 'Work Order'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
