# Generated by Django 5.2.6 on 2026-02-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_alter_documentlibrary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
