# Generated by Django 5.2.6 on 2026-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_customer_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfiguration',
            name='mapping_config',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping from incoming JSON keys to internal Customer fields'),
        ),
    ]
