# Generated by Django 5.2.6 on 2026-02-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_webhookconfiguration_mapping_config'),
        ('users', '0004_alter_organization_parent_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookconfiguration',
            name='organization',
        ),
        migrations.CreateModel(
            name='EndpointConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret_key', models.CharField(help_text='Secret key to be used in endpoint headers for authentication', max_length=255, unique=True)),
                ('mapping_config', models.JSONField(blank=True, default=dict, help_text='Mapping from incoming JSON keys to internal Customer fields')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_configs', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RawEndpointLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.endpointconfiguration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_leads', to='users.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='RawWebhookLead',
        ),
        migrations.DeleteModel(
            name='WebhookConfiguration',
        ),
    ]
