# Generated by Django 5.2.6 on 2026-02-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_remove_webhookconfiguration_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointconfiguration',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Secret key to be used in endpoint headers for authentication', max_length=255, unique=True),
        ),
    ]
