# Generated by Django 5.2.6 on 2026-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_alter_endpointconfiguration_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlibrary',
            name='document_purpose',
            field=models.CharField(choices=[('new_lead_email', 'New Lead Email'), ('booked_email', 'Booked Email'), ('closed_email', 'Closed Email'), ('invoice_email', 'Invoice Email'), ('receipt_email', 'Receipt Email'), ('estimate_email', 'Estimate Email'), ('general_email', 'General Email'), ('estimate_pdf', 'Estimate PDF'), ('invoice_pdf', 'Invoice PDF'), ('receipt_pdf', 'Receipt PDF'), ('work_order_pdf', 'Work Order PDF'), ('contract_pdf', 'Contract PDF'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
