# Generated by Django 5.2.6 on 2026-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0017_documentlibrary_document_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlibrary',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='attached_to_documents', to='masterdata.documentlibrary'),
        ),
        migrations.AlterField(
            model_name='documentlibrary',
            name='document_purpose',
            field=models.CharField(choices=[('new_lead_email', 'New Lead Email'), ('booked_email', 'Booked Email'), ('closed_email', 'Closed Email'), ('invoice_email', 'Invoice Email'), ('receipt_email', 'Receipt Email'), ('endpoint_leads_task', 'Endpoint Leads task'), ('estimate_pdf', 'Estimate PDF'), ('invoice_pdf', 'Invoice PDF'), ('receipt_pdf', 'Receipt PDF'), ('work_order_pdf', 'Work Order PDF'), ('contract_pdf', 'Contract PDF'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
