# Generated by Django 5.2.6 on 2026-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0018_documentlibrary_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlibrary',
            name='document_purpose',
            field=models.CharField(choices=[('new_lead_email', 'New Lead Email'), ('booked_email', 'Booked Email'), ('closed_email', 'Closed Email'), ('invoice_email', 'Invoice Email'), ('receipt_email', 'Receipt Email'), ('endpoint_leads_task', 'Endpoint Leads task'), ('estimate_pdf', 'Estimate PDF'), ('invoice_pdf', 'Invoice PDF'), ('receipt_pdf', 'Receipt PDF'), ('work_order_pdf', 'Work Order PDF'), ('contract_pdf', 'Contract PDF'), ('signed_documents_email', 'Signed Documents Email'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
