# Generated by Django 5.2.6 on 2026-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_alter_documentlibrary_document_purpose'),
        ('users', '0006_organization_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomsize',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='movetype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='roomsize',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together={('organization', 'service_type')},
        ),
    ]
