# Generated by Django 5.2.6 on 2026-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0020_alter_branch_name_alter_movetype_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new_lead", "New Lead"),
                    ("in_progress", "In Progress"),
                    ("opportunity", "Opportunity"),
                    ("booked", "Booked"),
                    ("closed", "Closed"),
                    ("bad_lead", "Bad Lead"),
                    ("lost", "Lost"),
                    ("legacy", "Legacy"),
                ],
                default="new_lead",
                max_length=50,
            ),
        ),
    ]
