# Generated by Django 5.2.6 on 2026-02-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_organization_parent_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked dashboards cannot be edited by non-admins.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='users.organization')),
                ('shared_with_roles', models.ManyToManyField(blank=True, related_name='shared_dashboards', to='users.organizationrole')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI Card'), ('chart', 'Chart'), ('table', 'Data Table'), ('list', 'Activity List')], max_length=50)),
                ('chart_library', models.CharField(choices=[('recharts', 'Recharts'), ('google_charts', 'Google Charts'), ('none', 'None')], default='none', max_length=50)),
                ('data_source', models.CharField(help_text="Key for the data provider (e.g., 'upcoming_jobs', 'lead_volume')", max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('layout', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
