# Generated by Django 5.2.6 on 2026-02-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardwidget_widget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='global_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Default global filters for the dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='click_action',
            field=models.CharField(choices=[('filter_dashboard', 'Filter Dashboard'), ('drill_down', 'Show Details'), ('navigate', 'Navigate to Page'), ('none', 'No Action')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='click_target',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='enable_click',
            field=models.BooleanField(default=False),
        ),
    ]
