# Generated by Django 5.2.6 on 2026-02-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboard_global_filters_and_more'),
        ('users', '0004_alter_organization_parent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='category',
            field=models.CharField(blank=True, help_text="Category for grouping templates (e.g., 'Sales', 'Finance')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Templates are pre-built dashboards that can be cloned.'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='users.organization'),
        ),
    ]
