# Generated by Django 5.2.6 on 2026-02-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_custommetric'),
        ('users', '0004_alter_organization_parent_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommetric',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_metrics', to='users.organization'),
        ),
    ]
