# Generated by Django 5.2.6 on 2026-02-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_custommetric_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('kpi', 'KPI - Single Metric'), ('trend', 'Trend - Time Series'), ('breakdown', 'Breakdown - Category Comparison'), ('funnel', 'Funnel - Stage Conversion'), ('table', 'Table - Records'), ('activity', 'Activity - Timeline'), ('Calendar', 'Calendar View')], max_length=50),
        ),
    ]
