# Generated by Django 5.2.6 on 2026-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_dashboardwidget_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_category',
            field=models.CharField(choices=[('metrics', 'Metrics & KPIs'), ('trends', 'Trends & Forecasting'), ('comparisons', 'Breakdowns & Comparisons'), ('activities', 'Activity & Lists'), ('filters', 'Filters & Controls')], default='metrics', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('kpi', 'KPI - Single Metric'), ('trend', 'Trend - Time Series'), ('breakdown', 'Breakdown - Category Comparison'), ('funnel', 'Funnel - Stage Conversion'), ('table', 'Table - Records'), ('activity', 'Activity - Timeline'), ('Calendar', 'Calendar View'), ('control', 'Control - Filter/Input')], max_length=50),
        ),
    ]
