# Generated by Django 5.2.6 on 2026-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systempermission_organization_organizationrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('company', 'Company'), ('franchisee', 'Franchisee'), ('contractor', 'Contractor')], default='company', max_length=50),
        ),
    ]
