# Generated by Django 5.2.6 on 2026-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_organization_parent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_business_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
