# Generated by Django 5.2.6 on 2026-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_organization_google_business_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Optional admin email for the organization, used for notifications such as Work Orders', max_length=254, null=True),
        ),
    ]
