# Generated by Django 4.2.13 on 2025-12-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0005_customer_branch_customer_destination_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charge_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Charge Category',
                'verbose_name_plural': 'Charge Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChargeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('charge_type', models.CharField(choices=[('per_lb', 'Per Pound'), ('percent', 'Percentage'), ('flat', 'Flat Fee'), ('hourly', 'Hourly')], max_length=20)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applies_to', models.CharField(choices=[('local', 'Local'), ('long_distance', 'Long Distance'), ('both', 'Both')], default='both', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Must be included in estimates')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='transactiondata.chargecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charge_definitions', to=settings.AUTH_USER_MODEL)),
                ('percent_applied_on', models.ForeignKey(blank=True, help_text='Only used if charge_type = percent. Defines what this percentage applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_charges', to='transactiondata.chargedefinition')),
            ],
            options={
                'verbose_name': 'Charge Definition',
                'verbose_name_plural': 'Charge Definitions',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_lbs', models.PositiveIntegerField(blank=True, null=True)),
                ('labour_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimates', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='masterdata.customer')),
                ('move_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='masterdata.movetype')),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EstimateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('move_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_templates', to='masterdata.movetype')),
            ],
            options={
                'verbose_name': 'Estimate Template',
                'verbose_name_plural': 'Estimate Templates',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=150)),
                ('charge_type', models.CharField(choices=[('per_lb', 'Per Pound'), ('percent', 'Percentage'), ('flat', 'Flat Fee'), ('hourly', 'Hourly')], max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_user_modified', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactiondata.chargedefinition')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactiondata.estimate')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactiondata.estimatetemplate'),
        ),
        migrations.CreateModel(
            name='TemplateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactiondata.chargedefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactiondata.estimatetemplate')),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'unique_together': {('template', 'charge')},
            },
        ),
    ]
