# Generated by Django 4.2.13 on 2025-12-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_customer_branch_customer_destination_address_and_more'),
        ('transactiondata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargedefinition',
            name='applies_to',
        ),
        migrations.AddField(
            model_name='chargedefinition',
            name='applies_to',
            field=models.ManyToManyField(blank=True, help_text='Move types this charge applies to. Leave empty for all move types.', related_name='charge_definitions', to='masterdata.movetype'),
        ),
    ]
