# Generated by Django 4.2.13 on 2025-12-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_customer_branch_customer_destination_address_and_more'),
        ('transactiondata', '0002_remove_chargedefinition_applies_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='move_type',
        ),
        migrations.RemoveField(
            model_name='estimatetemplate',
            name='move_type',
        ),
        migrations.AddField(
            model_name='estimate',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='masterdata.servicetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimatetemplate',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_templates', to='masterdata.servicetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargedefinition',
            name='applies_to',
            field=models.ManyToManyField(blank=True, help_text='Service types this charge applies to. Leave empty for all service types.', related_name='charge_definitions', to='masterdata.servicetype'),
        ),
    ]
