# Generated by Django 4.2.13 on 2025-12-10 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0005_customer_branch_customer_destination_address_and_more'),
        ('transactiondata', '0003_remove_estimate_move_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('estimate_created', 'Estimate Created'), ('estimate_updated', 'Estimate Updated'), ('estimate_sent', 'Estimate Sent to Customer'), ('estimate_approved', 'Estimate Approved'), ('estimate_rejected', 'Estimate Rejected'), ('customer_contacted', 'Customer Contacted'), ('note_added', 'Note Added'), ('status_changed', 'Status Changed'), ('other', 'Other Activity')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='masterdata.customer')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='transactiondata.estimate')),
            ],
            options={
                'verbose_name': 'Customer Activity',
                'verbose_name_plural': 'Customer Activities',
                'ordering': ('-created_at',),
            },
        ),
    ]
