# Generated by Django 4.2.13 on 2025-12-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0004_customeractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='customer_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='customer_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='link_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='public_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
