# Generated by Django 4.2.13 on 2025-12-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_customer_branch_customer_destination_address_and_more'),
        ('transactiondata', '0005_estimate_customer_responded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_signature', models.BooleanField(default=True)),
                ('customer_viewed', models.BooleanField(default=False)),
                ('customer_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_signed', models.BooleanField(default=False)),
                ('customer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_signature', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_documents', to='masterdata.documentlibrary')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactiondata.estimate')),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('estimate', 'document')},
            },
        ),
    ]
