# Generated by Django 4.2.13 on 2025-12-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0006_estimatedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedocument',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_documents', to='transactiondata.estimate'),
        ),
    ]
