# Generated by Django 4.2.13 on 2025-12-10 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactiondata', '0007_alter_estimatedocument_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSigningBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_token', models.CharField(max_length=100, unique=True)),
                ('link_active', models.BooleanField(default=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_batches', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_batch', to='transactiondata.estimate')),
            ],
            options={
                'verbose_name': 'Document Signing Batch',
                'verbose_name_plural': 'Document Signing Batches',
            },
        ),
    ]
