# Generated by Django 4.2.13 on 2025-12-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0008_documentsigningbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Tax percentage from customer's branch", max_digits=5),
        ),
    ]
