# Generated by Django 4.2.13 on 2025-12-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0009_estimate_tax_amount_estimate_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='delivery_date_from',
            field=models.DateField(blank=True, help_text='Delivery start date', null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='delivery_date_to',
            field=models.DateField(blank=True, help_text='Delivery end date', null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='pickup_date_from',
            field=models.DateField(blank=True, help_text='Pickup start date', null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='pickup_date_to',
            field=models.DateField(blank=True, help_text='Pickup end date', null=True),
        ),
    ]
