# Generated by Django 4.2.13 on 2025-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0010_estimate_delivery_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargedefinition',
            name='is_estimate_only',
            field=models.BooleanField(default=False, help_text='Only for specific estimates, not shown in configure'),
        ),
    ]
