# Generated by Django 4.2.13 on 2025-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0011_chargedefinition_is_estimate_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedocument',
            name='customer_text_inputs',
            field=models.TextField(blank=True, help_text='JSON with indexed text inputs: {"0": "text value", "1": "another value"}'),
        ),
        migrations.AlterField(
            model_name='estimatedocument',
            name='customer_signature',
            field=models.TextField(blank=True, help_text='JSON with indexed signatures: {"0": "base64...", "1": "base64..."}'),
        ),
    ]
