# Generated by Django 4.2.13 on 2025-12-16 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactiondata', '0012_estimatedocument_customer_text_inputs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Morning, Afternoon, Evening', max_length=100)),
                ('start_time', models.TimeField(help_text='Start time of the window')),
                ('end_time', models.TimeField(help_text='End time of the window')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Window',
                'verbose_name_plural': 'Time Windows',
                'ordering': ('display_order', 'start_time'),
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='delivery_time_window',
            field=models.ForeignKey(blank=True, help_text='Delivery arrival window', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_estimates', to='transactiondata.timewindow'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='pickup_time_window',
            field=models.ForeignKey(blank=True, help_text='Pickup arrival window', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_estimates', to='transactiondata.timewindow'),
        ),
    ]
