# Generated by Django 4.2.13 on 2025-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0013_timewindow_estimate_delivery_time_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated discount amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], help_text='Type of discount: flat amount or percentage', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount amount or percentage', max_digits=12, null=True),
        ),
    ]
