# Generated by Django 5.2.6 on 2026-01-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0015_chargecategory_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='public_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
