# Generated by Django 5.2.6 on 2026-01-28 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_alter_documentlibrary_category'),
        ('transactiondata', '0017_estimate_email_template_estimate_invoice_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimate_email_template',
            field=models.ForeignKey(blank=True, help_text='Email template for sending estimate PDFs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_email_estimates', to='masterdata.documentlibrary'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='invoice_email_template',
            field=models.ForeignKey(blank=True, help_text='Email template for sending invoice PDFs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_email_estimates', to='masterdata.documentlibrary'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='receipt_email_template',
            field=models.ForeignKey(blank=True, help_text='Email template for sending receipt PDFs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_email_estimates', to='masterdata.documentlibrary'),
        ),
    ]
