# Generated by Django 5.2.6 on 2026-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0018_estimate_estimate_email_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
