# Generated by Django 5.2.6 on 2026-02-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0019_invoice_email_sent_at_paymentreceipt_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('approved', 'Approved'), ('booked', 'Booked'), ('invoiced', 'Invoiced'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
