# Generated by Django 5.2.6 on 2026-02-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_customer_is_archived'),
        ('transactiondata', '0020_alter_estimate_status'),
        ('users', '0004_alter_organization_parent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='transactiondata.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='delivery_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='delivery_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='delivery_time_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_work_orders', to='transactiondata.timewindow'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='labour_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Snapshot of estimate notes or work order specific notes'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pickup_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pickup_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pickup_time_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_work_orders', to='transactiondata.timewindow'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.servicetype'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='weight_lbs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_order_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('approved', 'Approved'), ('work_order', 'Work Order'), ('booked', 'Booked'), ('invoiced', 'Invoiced'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work_orders', to='users.organization'),
        ),
    ]
