# Generated by Django 5.2.6 on 2026-02-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0021_invoice_work_order_workorder_delivery_date_from_and_more'),
        ('users', '0004_alter_organization_parent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.organization'),
        ),
    ]
