# Generated by Django 5.2.6 on 2026-02-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0024_estimate_assigned_to_invoice_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='email_template',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='estimate_email_template',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='invoice_email_template',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='invoice_template',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='payment_receipt_template',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='receipt_email_template',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='work_order_template',
        ),
    ]
