# Generated by Django 5.2.6 on 2026-02-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0018_documentlibrary_attachments_and_more'),
        ('transactiondata', '0025_remove_estimate_email_template_and_more'),
        ('users', '0005_organization_google_business_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivity',
            name='activity_type',
            field=models.CharField(choices=[('estimate_created', 'Estimate Created'), ('estimate_updated', 'Estimate Updated'), ('estimate_sent', 'Estimate Sent to Customer'), ('estimate_approved', 'Estimate Approved'), ('estimate_rejected', 'Estimate Rejected'), ('customer_contacted', 'Customer Contacted'), ('note_added', 'Note Added'), ('status_changed', 'Status Changed'), ('email_opened', 'Email Opened by Customer'), ('other', 'Other Activity')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('purpose', models.CharField(help_text='e.g., new_lead_email, invoice_email', max_length=100)),
                ('tracking_token', models.CharField(max_length=100, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='masterdata.customer')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactiondata.estimate')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactiondata.invoice')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='users.organization')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ('-sent_at',),
            },
        ),
    ]
