# Generated by Django 5.2.6 on 2026-03-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0026_alter_customeractivity_activity_type_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='transactiondata.estimate'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('payment', 'Payment')], default='payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactiondata.invoice'),
        ),
    ]
