# Generated by Django 5.2.6 on 2026-03-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondata', '0027_paymentreceipt_estimate_paymentreceipt_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorestimatelineitem',
            name='charge_type',
            field=models.CharField(choices=[('per_lb', 'Per Pound'), ('percent', 'Percentage'), ('flat', 'Flat Fee'), ('hourly', 'Hourly')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='contractorestimatelineitem',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used if charge_type = percent', max_digits=5, null=True),
        ),
    ]
