# Generated by Django 5.2.6 on 2026-03-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactiondata", "0028_contractorestimatelineitem_charge_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreceipt",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("e_transfer", "E-Transfer"),
                    ("cash", "Cash"),
                    ("certified_cheque", "Certified Cheque"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted by Contractor"),
                    ("completed", "Completed"),
                    ("disputed", "Disputed"),
                    ("cancelled", "Cancelled"),
                    ("not_booked", "Not Booked"),
                    ("booked", "Booked"),
                    ("in_progress", "Move in Progress"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transactiondata.invoice",
                    ),
                ),
            ],
            options={"ordering": ["display_order"],},
        ),
    ]
