# Generated by Django 5.2.6 on 2026-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactiondata", "0029_alter_paymentreceipt_payment_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estimate", old_name="external_notes", new_name="customer_notes",
        ),
        migrations.AddField(
            model_name="estimate",
            name="contractor_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes visible to contractors in the work order portal",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes not visible to customer or contractor",
            ),
        ),
    ]
